# Generated by Django 4.1.5 on 2023-01-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Types",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.IntegerField()),
                ("description", models.CharField(max_length=50)),
                (
                    "nature",
                    models.CharField(
                        choices=[("Entrada", "Saída")], default="Entrada", max_length=8
                    ),
                ),
                (
                    "sinal",
                    models.CharField(choices=[("+", "-")], default="+", max_length=2),
                ),
            ],
        ),
    ]
