# Generated by Django 4.1.3 on 2023-01-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Types",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.IntegerField()),
                ("date", models.DateTimeField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("cpf", models.CharField(max_length=11)),
                ("card", models.CharField(max_length=20)),
                ("hour", models.TimeField()),
                ("owner_store", models.CharField(max_length=20)),
                ("store_name", models.CharField(max_length=20)),
            ],
        ),
    ]
